baseURL = "http://courtneythurston.com/"
languageCode = "en-us"
title = "Courtney Thurston"
theme = "cocoa"

[[menu.main]]
name                   = "Home"
weight                 = -120
identifier             = "home"
url                    = "/"

[[menu.main]]
name                   = "Features"
weight                 = -110
identifier             = "features"
url                    = "/features/"

[params]
author                 = "Courtney Thurston"
cachebuster            = true                          # add the current unix timestamp in query string for cache busting css assets
email                  = "thurscon@gmail.com"
faviconfile            = "img/leaf.ico"
github                 = "//github.com/courtneythurston"
linkedin               = "//linkedin.com/in/thurscon"
